(()=>{if(window.__UBAA_OPEN__)return;window.__UBAA_OPEN__=true;
const KEY="ubaa.settings.v1",D={endpoint:"https://api.openai.com/v1/chat/completions",model:"gpt-4o-mini",apiKey:""};
const esc=s=>String(s??"").replace(/[&<>"]/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[c]));
const load=()=>{try{return Object.assign({},D,JSON.parse(localStorage.getItem(KEY)||"{}"))}catch{return Object.assign({},D)}};
const save=x=>localStorage.setItem(KEY,JSON.stringify(x));
const page=()=>{const selection=String(window.getSelection?.()||"").trim();return{title:document.title,url:location.href,selection,text:(document.body?.innerText||"").replace(/\s+/g," ").trim().slice(0,12000)}};
const style=document.createElement("style");style.textContent="#ubaa{position:fixed;z-index:2147483647;right:18px;bottom:18px;width:min(430px,calc(100vw - 36px));height:min(680px,calc(100vh - 36px));background:#fff;color:#111;border:1px solid #bbb;border-radius:14px;box-shadow:0 12px 45px #0004;font:14px system-ui,sans-serif;display:flex;flex-direction:column;overflow:hidden}#ubaa *{box-sizing:border-box}#ubaa header{padding:12px 14px;border-bottom:1px solid #ddd;display:flex;justify-content:space-between;align-items:center;font-weight:700}#ubaa button{border:1px solid #bbb;background:#fff;border-radius:8px;padding:7px 10px;cursor:pointer}#ubaa textarea,#ubaa input{width:100%;border:1px solid #bbb;border-radius:8px;padding:9px;font:inherit}#ubaa main{padding:12px;overflow:auto;flex:1}.m{padding:10px 11px;border-radius:10px;margin:8px 0;white-space:pre-wrap;overflow-wrap:anywhere}.u{background:#eee}.a{background:#f7f7f7}#ubaa footer{border-top:1px solid #ddd;padding:10px;display:grid;gap:8px}.row{display:flex;gap:7px}.row>*{flex:1}.muted{font-size:12px;color:#666}.settings{display:none;gap:7px;padding:10px;border-bottom:1px solid #ddd;background:#fafafa}.settings.open{display:grid}";
document.documentElement.appendChild(style);
const root=document.createElement("div");root.id="ubaa";root.innerHTML='<header><span>Universal AI Assistant</span><div class="row"><button id="set">⚙</button><button id="close">×</button></div></header><section class="settings" id="settings"><input id="endpoint" placeholder="API endpoint"><input id="model" placeholder="Model"><input id="key" type="password" placeholder="API key"><button id="save">Save settings</button></section><main id="log"><div class="m a">Ready. Page context is available.</div></main><footer><div class="muted" id="context"></div><textarea id="q" rows="3" placeholder="Ask about this page..."></textarea><button id="send">Send</button></footer>';
document.body.appendChild(root);
const $=id=>root.querySelector("#"+id),cfg=load();$("endpoint").value=cfg.endpoint;$("model").value=cfg.model;$("key").value=cfg.apiKey;
const refresh=()=>{const p=page();$("context").textContent=(p.selection?"Selected text included. ":"")+"Page: "+p.title.slice(0,80);return p};refresh();
$("set").onclick=()=>$("settings").classList.toggle("open");$("close").onclick=()=>{root.remove();style.remove();window.__UBAA_OPEN__=false};
$("save").onclick=()=>{save({endpoint:$("endpoint").value.trim(),model:$("model").value.trim(),apiKey:$("key").value});$("settings").classList.remove("open")};
$("send").onclick=async()=>{const q=$("q").value.trim();if(!q)return;const p=refresh(),c=load();$("log").insertAdjacentHTML("beforeend",'<div class="m u">'+esc(q)+"</div>");$("q").value="";const out=document.createElement("div");out.className="m a";out.textContent="Thinking…";$("log").appendChild(out);if(!c.apiKey){out.textContent="Open ⚙ and add your API key.";return}
const messages=[{role:"system",content:"You are a helpful browser assistant. Use only the supplied webpage context. Be concise unless detail is useful."},{role:"user",content:"Question:\n"+q+"\n\nTITLE: "+p.title+"\nURL: "+p.url+"\nSELECTED TEXT: "+(p.selection||"(none)")+"\nPAGE TEXT:\n"+p.text}];
try{const r=await fetch(c.endpoint,{method:"POST",headers:{"Content-Type":"application/json","Authorization":"Bearer "+c.apiKey},body:JSON.stringify({model:c.model,messages,temperature:.2})});const data=await r.json();if(!r.ok)throw Error(data?.error?.message||"HTTP "+r.status);out.textContent=data?.choices?.[0]?.message?.content||"No answer returned."}catch(e){out.textContent="Error: "+e.message}$("log").scrollTop=$("log").scrollHeight};
$("q").addEventListener("keydown",e=>{if((e.ctrlKey||e.metaKey)&&e.key==="Enter")$("send").click()});
})();